### ISSUE TITLE
`inbound_liquidity_msats` is confusing

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk-greenlight#1018]
The `inbound_liquidity_msats` in `NodeState` currently shows the largest receivable amount on a single channel. For integrations like the btcpay server integration that's confusing when people want to maximize their inbound liquidity. `inbound_liquidity_msats` should probably contain the _total_ receivable amount on all your channels. 

We have to make sure that internally we keep using the max receivable amount on a single channel for invoices though, and also have a field that clients can use to calculate fees.

**Comment by ok300** [comment]
Fixed in #1062
