### ISSUE TITLE
Cannot start reverse-swap that sends all funds: Paying HOLD invoice timed out

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk-greenlight#1074]
On node `02918f627bfc2a86469f48a808045d4dee49cda2a85b6a6a15e4e0eab291060993`, we cannot start a reverse-swap that sends out all funds. It always returns error `Generic: Trying to pay the HODL invoice timed out: deadline has elapsed`.

The balance was ~785k sats. We also tried getting the balance lower and the behaviour did not change when the balance was ~585k sats.

The reverse-swap invoice for the initial swap is: `lnbc7854510n1pnt5mhppp5pd3rftcyym74qhas5h9qv3yxfyx8gyhax26yxlhqhg3g2q78a99qdql2djkuepqw3hjqsj5gvsxzerywfjhxuccqzylxqyp2xqrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqrx8lgqq04qqqyqqqqqqqqqqqqqq9qrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqrx845qqsdsqqyqqqqqqqqqqqqqq9qsp5axsvh5rq5krcqc9ttky6gst6nnughj95s64cxutwx298xntez39q9qxpqysgq2j68606m5ss5n5gkz6h3q9pjg8wutrqj8zxuuej6q23yqazrh3sre78ven323zxceg4grahjlj90vrqj43zqaf98vlq0gk5yx0u4nvcp96t3k8`

I can provide additional logs in case they are helpful.

**Comment by ok300** [comment]
> `Generic: Trying to pay the HODL invoice timed out: deadline has elapsed`

The `deadline has elapsed` error comes from the GL node.

Can you please provide SDK logs from when these errors happened? That will hopefully contain more details about which specific deadline elapsed and why.

**Comment by ok300** [comment]
This was solved in the meantime, so I'm closing the ticket.

Please let us know if it happens again.

**Comment by ok300** [comment]
@andrei-21 if it's still happening, can you please post the following, as it will help us troubleshoot?
- the diagnostic data for that node (`sdk.generate_diagnostic_data`)
- the SDK logs that cover the triggering of that payment until the failure
