### ISSUE TITLE
Breez / Greenlight on BTCPayServer - Payments keep failing

### ISSUE THREAD

**Issue by Lachie-McW** [breez/breez-sdk-greenlight#1089]
I've set up the Breez/Greenlight plugin on BTCPayServer (https://docs.btcpayserver.org/Breez/)

I have done a swap in and made a large payment to my phoenix wallet so I have plenty of inbound liquidity (over 600,000 sats).

The problem is I cannot make lightning payments TO my BTCPayServer from Phoenix or WoS. I'm trying to send 10,000 sats and the payments keep failing. Phoenix states the reason as "Fee is insufficient".

I also notice this error message on the lightning node connection:
"Connection to the Lightning node successful, but no public address has been configured"
How do I configure a public address?

Would appreciate some help please

**Comment by kingonly** [comment]
Handled via telegram
