### ISSUE TITLE
Bug: `list_refundables` keeps returning refunded swap while refund tx is pending in mempool

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk-greenlight#1116]
As the title describes, we've found that when refunding a failed swap, while the refund tx is in the mempool, `list_refundables` continues to return the swap as refundable. 

I don't think it's related, but when we experienced this, we were refunding towards ourselves using a new swap address.

**Comment by roeierez** [comment]
@danielgranhao this is actually by design so the app can bump the fees and broadcast another refund in case the tx is stuck in the mempool for example.
Do you see any issue with that?

**Comment by danielgranhao** [comment]
Thanks for the explanation, @roeierez. So, if we want to show only actionable items, we have to filter out swaps that have a pending refund tx. It's probably enough to check that there is something in `SwapInfo.refund_tx_ids`. If that's the case, that would cover our needs.
