### ISSUE TITLE
setLogStream() OnceCell - unable to re-init logging

### ISSUE THREAD

**Issue by neveero** [breez/breez-sdk-greenlight#1130]
rerunning ``setLogStream()`` returns ``Generic: Log stream already created`` unless the app is killed and restarted.  I suspect it is due to the protection on the Rust side as I have tried the usual tricks in Kotlin and still get the same response:

``static LOG_INIT: OnceCell<bool> = OnceCell::new();``

https://github.com/breez/breez-sdk-greenlight/blob/18ab125c90b2f6a7e8f4e66e09aa6bd73133d88e/libs/sdk-bindings/src/uniffi_binding.rs#L37

I would like to be able to re-init the setLogStream() so that the logging can be enabled/disabled without restarting the app.  The log files fill up quite quickly so it would be useful to be able to auto disable logging after 10 minutes, if the user forgets to turn off logging/restart the app, in order to prevent crashing.

**Comment by neveero** [comment]
If anyone else comes across this issue, a slightly better result is if you delete the log file, new logs will stop being written.  If the user wants to run another logging session they will need to kill the app, force stop if running a service, even if you recreate the file, it wont log to it again.  But I can now prevent crashing due to users leaving logging on.

**Comment by dangeross** [comment]
Assuming you are writing all log stream entries to file, can't you add a flag to the application whether to write entries to file of not?

**Comment by neveero** [comment]
I was so busy trying to re-init ```setLogStream()``` that I didn't think of trying to live manipulate the stream from within ```CustomLogListener()``` - that is definitely better than the files approach as shouldn't need the Force Stop anymore to restart logging.  Thank you!

I do think it would be better to be able to turn off the stream though, especially with a background service running.  I can disconnect and connect again, but seems strange I can't change/clear the log stream originally sent to rust between those 2 operations.  It's only on Force Stop and my relaunch (and my init argument not to enable it in the first place being set) that I can stop it running the stream.  Talk is cheap though so if I can figure out rust some more, ill dive into it deeper and hopefully send a PR.

**Comment by neveero** [comment]
Brilliant!  That's a great idea, thank you for the example too!

**Comment by ok300** [comment]
Closing this, as it looks like the original question was answered.
