### ISSUE TITLE
Cannot remove a registered webhook URL

### ISSUE THREAD

**Issue by jose31canizar** [breez/breez-sdk-greenlight#730]
Currently there is no way to remove a registered webhook URL. So after changing a query param in the url, for example the language param, it will register an additional webhook and thus the device will receive two notifications for every payment. It would be great to have the capability of removing a previously registered webhook so users can re-register with a different language.

**Comment by JssDWt** [comment]
This needs some infrastructure updates and sdk support. Reopening.
