### ISSUE TITLE
Remove a registered webhook URL

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk-greenlight#832]
This is an umbrella-issue to track all necessary changes for this feature.

- [x] Add support to remove webhook URL
  - [x] LSPD (for payment notifications): https://github.com/breez/lspd/pull/194
  - [x] Breez server: https://github.com/breez/server/pull/44
  - [x] chainnotifier (for swap notifications): https://github.com/breez/chainnotifier/pull/6
  - [x] SDK & CLI: https://github.com/breez/breez-sdk/pull/920
- ~SDK: When changing LSP, remove webhooks from old LSP~
- [x]  Add docs snippet: https://github.com/breez/breez-sdk-docs/pull/151

Fixes #730

**Comment by JssDWt** [comment]
> SDK: When changing LSP, remove webhooks from old LSP
Maybe this isn't necessary. Note that if you already have a channel with that LSP, it could be useful to keep the webhook available for if you're receiving a payment over that channel.

**Comment by dangeross** [comment]
Closing as all tasks are merged
